/**
 * Guided story steps (Segel & Heer "interactive slideshow"): What happened →
 * The verdict → The evidence → The suspects → The options → The plan → Export.
 * Step definitions live here in UI config — the store only carries the cursor.
 * Bodies are computed from live store values at render time.
 */
import type { AppState, TabId } from '../../state/store';
import { fmtPct, fmtUsd } from '../shared/format';

export interface StoryStep {
  id: string;
  title: string;
  tab: TabId;
  /** Section anchor to scroll into view after the tab switch */
  anchorId?: string;
  /** optional selection side effect applied on entry */
  apply?: (s: AppState) => void;
  body: (s: AppState) => string;
}

export const STORY_STEPS: StoryStep[] = [
  {
    id: 'shook',
    title: 'Something shook',
    tab: 'flightdeck',
    body: (s) =>
      `Flight ${s.evidence?.anomaly.flightRef ?? '—'} exceeded its vibration limit in the final seconds and the helicopter auto-grounded itself. This is the reconstructed flight — scrub it, slow it down.`,
  },
  {
    id: 'verdict',
    title: 'The verdict',
    tab: 'briefing',
    body: (s) => {
      const top = s.bayes?.posteriors[0];
      return top
        ? `TRIAGE's answer up front: ${top.name.toLowerCase()}, ${fmtPct(top.posterior)} confidence. Everything after this shows how that number was earned.`
        : 'The briefing summarizes whatever the loaded files support.';
    },
  },
  {
    id: 'evidence',
    title: 'The evidence',
    tab: 'workbench',
    anchorId: 'evidence-stream',
    apply: (s) => {
      // spotlight the strongest exceedance finding
      const item = s.evidence?.items
        .filter((i) => i.kind === 'exceedance')
        .sort((a, b) => b.weight - a.weight)[0];
      if (item) s.selectEvidence(item.id);
    },
    body: (s) =>
      `${s.evidence?.items.length ?? 0} findings were computed from the raw mission files — trends, regressions, maintenance correlations. Every one links back to its source rows. No number in this app is generated by AI.`,
  },
  {
    id: 'suspects',
    title: 'Nine suspects, one leader',
    tab: 'workbench',
    anchorId: 'hypothesis-rail',
    apply: (s) => {
      const top = s.bayes?.posteriors[0];
      if (top) s.selectHypothesis(top.hypothesisId);
    },
    body: (s) => {
      const top = s.bayes?.posteriors[0];
      return top
        ? `Each candidate cause starts from fleet history and gets pushed up or down by the evidence. ${top.name} ends at ${fmtPct(top.posterior)} — open "show the math" to audit every step.`
        : 'Each candidate cause is weighed by the evidence.';
    },
  },
  {
    id: 'options',
    title: 'What each option costs',
    tab: 'decision',
    anchorId: 'action-table',
    body: (s) => {
      const d = s.decision;
      const rec = d?.actions.find((a) => a.actionId === d.recommendedActionId);
      return rec && d
        ? `${d.actions.length} action plans, costed across every possible cause — including the risk of losing the helicopter. "${rec.name}" wins at ${fmtUsd(rec.expectedRiskAdjustedCostUsd)} expected.`
        : 'Each action plan is priced across all possible causes.';
    },
  },
  {
    id: 'confirm',
    title: 'How we make sure',
    tab: 'triage',
    anchorId: 'plan-timeline',
    body: (s) => {
      const t = s.triage;
      const d = s.decision;
      return t
        ? `A ${t.steps.length}-step test sequence, ordered by which tests separate the suspects fastest — done by Sol ${t.completionSol}${
            d ? `, ${d.schedule.effectiveDeadlineSol.value - t.completionSol} Mars days to spare` : ''
          }. Every step names its if/then outcomes and ranked personnel.`
        : 'The diagnosis plan orders the most informative tests first.';
    },
  },
  {
    id: 'export',
    title: 'Take it to the board',
    tab: 'export',
    body: () =>
      'The whole case — every number, citation and caveat — exports as a review-board packet: Markdown, HTML, or print-to-PDF. TRIAGE advises; humans decide.',
  },
];
